// <auto-generated />
using System;
using ERPEscolar.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ERPEscolar.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115044354_AddPeriodoCalificacionProperties")]
    partial class AddPeriodoCalificacionProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlumnoTutor", b =>
                {
                    b.Property<int>("AlumnosId")
                        .HasColumnType("integer");

                    b.Property<int>("TutoresId")
                        .HasColumnType("integer");

                    b.HasKey("AlumnosId", "TutoresId");

                    b.HasIndex("TutoresId");

                    b.ToTable("AlumnoTutor");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CURP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricula")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CURP")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.HasIndex("SchoolId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int?>("DocenteQueRegistroId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrupoMateriaId")
                        .HasColumnType("integer");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("RegistradoPor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("DocenteQueRegistroId");

                    b.HasIndex("GrupoMateriaId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Beca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Justificacion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.ToTable("Becas");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.BitacoraFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CFDIId")
                        .HasColumnType("integer");

                    b.Property<int?>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetalleError")
                        .HasColumnType("text");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPOrigen")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CFDIId");

                    b.HasIndex("CargoId");

                    b.HasIndex("Timestamp");

                    b.ToTable("BitacorasFiscales");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.CFDI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CURP_Alumno")
                        .HasColumnType("text");

                    b.Property<string>("CadenaOriginal")
                        .HasColumnType("text");

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("ClaveCT")
                        .HasColumnType("text");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<string>("ErrorTimbrado")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaTimbrado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("IVA")
                        .HasColumnType("numeric");

                    b.Property<string>("NivelEducativo")
                        .HasColumnType("text");

                    b.Property<string>("NombreReceptor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RFC_Emisor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RFC_Receptor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonCancelacion")
                        .HasColumnType("text");

                    b.Property<int>("ReintentosTimbrado")
                        .HasColumnType("integer");

                    b.Property<string>("RutaPDF")
                        .HasColumnType("text");

                    b.Property<string>("RutaXML")
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XMLConTimbrado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("Serie", "Folio")
                        .IsUnique();

                    b.ToTable("CFDIs");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Aprobado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Calificacion1")
                        .HasColumnType("numeric");

                    b.Property<int?>("DocenteQueQualificaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCalificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrupoMateriaId")
                        .HasColumnType("integer");

                    b.Property<int?>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<int>("PeriodoCalificacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("DocenteQueQualificaId");

                    b.HasIndex("GrupoMateriaId");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("PeriodoCalificacionId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<int>("ConceptoCobroId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("IVA")
                        .HasColumnType("numeric");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoRecibido")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CicloEscolarId");

                    b.HasIndex("ConceptoCobroId");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.CicloEscolar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("CiclosEscolares");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ComplementoEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CFDIId")
                        .HasColumnType("integer");

                    b.Property<string>("CURP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaveCT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaExpedicion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelEducativo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoExamenGeneral")
                        .HasColumnType("text");

                    b.Property<bool>("ValidadoSAT")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CFDIId");

                    b.ToTable("ComplementosEducativos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ConceptoCobro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoBase")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoConcepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("ConceptosCobro");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ConfiguracionCFDI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Contrasena_PAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiasCadenaOriginal")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrlRuta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProvedorTimbrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReintentosMaximos")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoEsperaReintentos")
                        .HasColumnType("integer");

                    b.Property<string>("UrlWSCancelacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlWSTimbrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Usuario_PAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("ConfiguracionesCFDI");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ConfiguracionFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("CertificadoRutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClavePrivada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClavePrivadaRutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PorcentajeISR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PorcentajeIVA")
                        .HasColumnType("numeric");

                    b.Property<string>("ProveedorTimbrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegimenFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenTimbrado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("ConfiguracionesFiscales");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CURP")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CapacidadMaxima")
                        .HasColumnType("integer");

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<int?>("DocenteTutorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId");

                    b.HasIndex("DocenteTutorId");

                    b.HasIndex("SchoolId", "CicloEscolarId", "Nombre")
                        .IsUnique();

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.GrupoMateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("GrupoId", "MateriaId", "DocenteId")
                        .IsUnique();

                    b.ToTable("GrupoMaterias");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("AlumnoId", "GrupoId", "CicloEscolarId")
                        .IsUnique();

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Creditos")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int?>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("SchoolId", "Clave")
                        .IsUnique();

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<string>("BancoOrigen")
                        .HasColumnType("text");

                    b.Property<int?>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Comprobante")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaDepósito")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("CargoId");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.PeriodoCalificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("Cerrado")
                        .HasColumnType("boolean");

                    b.Property<int>("CicloEscolarId")
                        .HasColumnType("integer");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CicloEscolarId");

                    b.HasIndex("SchoolId");

                    b.ToTable("PeriodosCalificacion");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revocado")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.RolePermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermisos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ClaveCT")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RFC")
                        .IsUnique();

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CURP")
                        .HasColumnType("text");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrincipalResponsable")
                        .HasColumnType("boolean");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tutores");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("CambioPasswordRequerido")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AlumnoTutor", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Alumno", null)
                        .WithMany()
                        .HasForeignKey("AlumnosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Alumno", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany("Alumnos")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Asistencia", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Alumno", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("AlumnoId");

                    b.HasOne("ERPEscolar.API.Models.Docente", "DocenteQueRegistro")
                        .WithMany("AsistenciasRegistradas")
                        .HasForeignKey("DocenteQueRegistroId");

                    b.HasOne("ERPEscolar.API.Models.GrupoMateria", "GrupoMateria")
                        .WithMany("Asistencias")
                        .HasForeignKey("GrupoMateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Inscripcion", "Inscripcion")
                        .WithMany("Asistencias")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocenteQueRegistro");

                    b.Navigation("GrupoMateria");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Beca", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.BitacoraFiscal", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.CFDI", "CFDI")
                        .WithMany("Bitacoras")
                        .HasForeignKey("CFDIId");

                    b.HasOne("ERPEscolar.API.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId");

                    b.Navigation("CFDI");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.CFDI", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Cargo", "Cargo")
                        .WithMany("CFDIs")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Calificacion", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Alumno", "Alumno")
                        .WithMany("Calificaciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Docente", "DocenteQueQualifica")
                        .WithMany()
                        .HasForeignKey("DocenteQueQualificaId");

                    b.HasOne("ERPEscolar.API.Models.GrupoMateria", "GrupoMateria")
                        .WithMany("Calificaciones")
                        .HasForeignKey("GrupoMateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Inscripcion", null)
                        .WithMany("Calificaciones")
                        .HasForeignKey("InscripcionId");

                    b.HasOne("ERPEscolar.API.Models.PeriodoCalificacion", "PeriodoCalificacion")
                        .WithMany("Calificaciones")
                        .HasForeignKey("PeriodoCalificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("DocenteQueQualifica");

                    b.Navigation("GrupoMateria");

                    b.Navigation("PeriodoCalificacion");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Cargo", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Alumno", "Alumno")
                        .WithMany("Cargos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.CicloEscolar", "CicloEscolar")
                        .WithMany()
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.ConceptoCobro", "ConceptoCobro")
                        .WithMany("Cargos")
                        .HasForeignKey("ConceptoCobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("CicloEscolar");

                    b.Navigation("ConceptoCobro");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.CicloEscolar", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany("CiclosEscolares")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ComplementoEducativo", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.CFDI", "CFDI")
                        .WithMany()
                        .HasForeignKey("CFDIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CFDI");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ConceptoCobro", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany("ConceptosCobro")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ConfiguracionCFDI", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ConfiguracionFiscal", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Docente", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany("Docentes")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.User", "User")
                        .WithOne("Docente")
                        .HasForeignKey("ERPEscolar.API.Models.Docente", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Grupo", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.CicloEscolar", "CicloEscolar")
                        .WithMany("Grupos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Docente", "DocenteTutor")
                        .WithMany("Grupos")
                        .HasForeignKey("DocenteTutorId");

                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany("Grupos")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CicloEscolar");

                    b.Navigation("DocenteTutor");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.GrupoMateria", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Grupo", "Grupo")
                        .WithMany("GrupoMaterias")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Materia", "Materia")
                        .WithMany("GrupoMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Grupo");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Inscripcion", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.CicloEscolar", "CicloEscolar")
                        .WithMany()
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Grupo", "Grupo")
                        .WithMany("Inscripciones")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("CicloEscolar");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Materia", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Docente", null)
                        .WithMany("Materias")
                        .HasForeignKey("DocenteId");

                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Pago", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Alumno", "Alumno")
                        .WithMany("Pagos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Cargo", "Cargo")
                        .WithMany("Pagos")
                        .HasForeignKey("CargoId");

                    b.Navigation("Alumno");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.PeriodoCalificacion", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.CicloEscolar", "CicloEscolar")
                        .WithMany("Periodos")
                        .HasForeignKey("CicloEscolarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CicloEscolar");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.RefreshToken", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.RolePermiso", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Permiso", "Permiso")
                        .WithMany("RolePermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.Role", "Role")
                        .WithMany("RolePermisos")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.UserRole", b =>
                {
                    b.HasOne("ERPEscolar.API.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERPEscolar.API.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Alumno", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Calificaciones");

                    b.Navigation("Cargos");

                    b.Navigation("Inscripciones");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.CFDI", b =>
                {
                    b.Navigation("Bitacoras");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Cargo", b =>
                {
                    b.Navigation("CFDIs");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.CicloEscolar", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Periodos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.ConceptoCobro", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Docente", b =>
                {
                    b.Navigation("AsistenciasRegistradas");

                    b.Navigation("Grupos");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Grupo", b =>
                {
                    b.Navigation("GrupoMaterias");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.GrupoMateria", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Inscripcion", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Materia", b =>
                {
                    b.Navigation("GrupoMaterias");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.PeriodoCalificacion", b =>
                {
                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Permiso", b =>
                {
                    b.Navigation("RolePermisos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.Role", b =>
                {
                    b.Navigation("RolePermisos");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.School", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("CiclosEscolares");

                    b.Navigation("ConceptosCobro");

                    b.Navigation("Docentes");

                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("ERPEscolar.API.Models.User", b =>
                {
                    b.Navigation("Docente");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
